#title
titleBg=#DDE3F2
closeBtnBgIn=#C43C45
miniBtnBgIn=#A9B6DB
mainPanelBg=#A9B6DB
#lock
lockBg=#EEF2F8
lockTipLabel=#233A70
lockSecretText=#2A4C8F
lockSecretTextBorder=#9FB0D3
loginTip=#2F355C
isLocalBg=#365C9A
isLocalSelectBg=#7789B8
isCreateScene=#FFFFFF
isCreateSelectBg=#2E3F78
isCreateBg=#B8C4E3
isLightWeightVersion=#FFFFFF
isLightBg=#3A4D8F
isLightSelectBg=#C5CEE6
isLightBorder=#FFFFFF
isEng=#FFFFFF
isEngBg=#42579D
isEngContextSelect=#FFFFFF
isEngContextSelectBg=#2F427B
isEngContext=#1E2438
isEngContextBg=#E5E9F4
isEngSelectBg=#3A4D8F
lookFun=#FFFFFF
lookFunBg=#6C7EB3

#main
contentPaneBg=#EEF2F8
tableBg=#F2F4F8
tableSelectBg=#D9E0EF
tableSelectFore=#2F355C
tableGrid=#B3BED5
scrollPaneBg=#EEF2F8
scrollPaneBor=#6C7EB3
menuItemBlinkBgIn=#E5C769
menuItemBlinkBgOut=#F7F6F1
menuItemBlinkBorIn=#D8B84F
menuItemBlinkBorOut=#FFFFFF
searchTipFore=#2A3E72
searchText=#2A3E72
searchTextBlinkBorIn=#3D5A97
searchTextBlinkBorOut=#B8C4E3
searchBtnFore=#FFFFFF
searchBtnBg=#233A70
searchBtnBlinkBorIn=#FFFFFF
addBtnFore=#FFFFFF
addBtnBg=#4A5F9F
addBtnBlinkBorIn=#FFFFFF
resultNumbersFore=#2F355C
copyAlertLabelFore=#C43C45
clearBtnFore=#FFFFFF
clearBtnBg=#7F8FB9
clearBtnBorderIn=#D9E0EF
realTimeBtnFore=#FFFFFF
realTimeBtnBg=#A56D1A
realTimeBtnSelect=#42579D
realTimeBtnBorderIn=#FFFFFF
switchBtnFore=#1E2438
switchBtnBg=#6173A9
switchBtnBorderIn=#FFFFFF
logBtnFore=#1E2438
logBtnBg=#BEC8DE
logBtnBorderIn=#FFFFFF
funcBtnFore=#1E2438
funcBtnBg=#D5DCEF
funcBtnBorderIn=#FFFFFF
disclaimLabel=#D74C56
aboutBtnFore=#1E2438
aboutBtnBg=#DDE3F2
aboutBtnBlinkBorIn=#FFFFFF
exportBtnFore=#FFFFFF
exportBtnBg=#2F427B
exportBtnBlinkBorIn=#FFFFFF
importBtnFore=#FFFFFF
importBtnBg=#3A4D8F
importBtnBlinkBorIn=#FFFFFF
activistTimeLabel=#3D5A97
activeBtnFore=#E6EAF3
activeBtnBg=#233A70
activeBtnSelect=#233A70
activeBtnBgSelect=#8DA1CB
activeBtnBlinkBorIn=#FFFFFF
importBtn3Fore=#FFFFFF
importBtn3Bg=#365C9A
importBtn4Fore=#FFFFFF
importBtn4Bg=#3E827C
outputAreaBg=#EEF2F8
outputAreaFore1=#666666
outputAreaFore2=#3F4E88
outputAreaBor=#6C7EB3
configurableBtnBg=#6C7EB3
importByEncryptBtnBg=#2B3969
#main-scrollBar
handle=#2F355C
upBtn=#FFFFFF
downBtn=#FFFFFF
#about
aboutContentPaneBg=#EEF2F8
developerLabel=#2F355C
versionLabel=#4A5F9F
recentlyDate=#365C9A
statement=#8F324D
copyRight=#2A4C8F
#add
addContentPaneBg=#EEF2F8
textFieldBlinkBorIn1=#3D5A97
textFieldBlinkBorOut1=#B3BED5
textFieldBlinkBorIn2=#3D5A97
textFieldBlinkBorOut2=#B3BED5
textFieldBlinkBorIn3=#3D5A97
textFieldBlinkBorOut3=#B3BED5
surePassBlinkBorIn=#3D5A97
surePassBlinkBorOut=#B3BED5
textFieldBlinkBorIn4=#3D5A97
textFieldBlinkBorOut4=#B3BED5
resetBtnFore=#FFFFFF
resetBtnBg=#B8C4E3
resetBtnBlinkBorIn=#FFFFFF
generateBtnFore=#FFFFFF
generateBtnBg=#98A8D0
generateBtnBlinkBorIn=#FFFFFF
submitBtnFore=#FFFFFF
submitBtnBg=#6C7EB3
submitBtnBlinkBorIn=#FFFFFF
#exportImport
pathTextFore=#3A4D8F
pathTextLineBor=#B8C4E3
chooseFileBtnFore=#FFFFFF
chooseFileBtnBg=#B8C4E3
sureBtnFore=#FFFFFF
sureBtnBg=#2F427B
