#title
titleBg=#F2E7DE
closeBtnBgIn=#C43C45
miniBtnBgIn=#D9B79E
mainPanelBg=#D9B79E
#lock
lockBg=#F7F1EB
lockTipLabel=#8A4A23
lockSecretText=#A55A2A
lockSecretTextBorder=#DDB496
loginTip=#6F4330
isLocalBg=#B05E2E
isLocalSelectBg=#C68352
isCreateScene=#FFFFFF
isCreateSelectBg=#8A4A23
isCreateBg=#E3C7AF
isLightWeightVersion=#FFFFFF
isLightBg=#9B5628
isLightSelectBg=#F0DDCC
isLightBorder=#FFFFFF
isEng=#FFFFFF
isEngBg=#9B5628
isEngContextSelect=#FFFFFF
isEngContextSelectBg=#8A4A23
isEngContext=#5C3424
isEngContextBg=#F4E7DC
isEngSelectBg=#B05E2E
lookFun=#FFFFFF
lookFunBg=#C68352
#main
contentPaneBg=#F7F1EB
tableBg=#FAF5F0
tableSelectBg=#ECD6C4
tableSelectFore=#6E3D24
tableGrid=#D7B9A3
scrollPaneBg=#F7F1EB
scrollPaneBor=#C68352
menuItemBlinkBgIn=#E5C769
menuItemBlinkBgOut=#F7F6F1
menuItemBlinkBorIn=#D8B84F
menuItemBlinkBorOut=#FFFFFF
searchTipFore=#8A4A23
searchText=#8A4A23
searchTextBlinkBorIn=#B05E2E
searchTextBlinkBorOut=#E3C7AF
searchBtnFore=#FFFFFF
searchBtnBg=#7B3F1C
searchBtnBlinkBorIn=#FFFFFF
addBtnFore=#FFFFFF
addBtnBg=#B05E2E
addBtnBlinkBorIn=#FFFFFF
resultNumbersFore=#7B3F1C
copyAlertLabelFore=#C43C45
clearBtnFore=#FFFFFF
clearBtnBg=#C68352
clearBtnBorderIn=#ECD6C4
realTimeBtnFore=#FFFFFF
realTimeBtnBg=#8F5A1F
realTimeBtnSelect=#D9B079
realTimeBtnBorderIn=#FFFFFF
switchBtnFore=#5C3424
switchBtnBg=#D2A277
switchBtnBorderIn=#FFFFFF
logBtnFore=#FFFFFF
logBtnBg=#8A4A23
logBtnBorderIn=#FFFFFF
funcBtnFore=#FFFFFF
funcBtnBg=#7B3F1C
funcBtnBorderIn=#FFFFFF
disclaimLabel=#D74C56
aboutBtnFore=#5C3424
aboutBtnBg=#E7D1BF
aboutBtnBlinkBorIn=#FFFFFF
exportBtnFore=#FFFFFF
exportBtnBg=#8F4A1E
exportBtnBlinkBorIn=#FFFFFF
importBtnFore=#FFFFFF
importBtnBg=#B05E2E
importBtnBlinkBorIn=#FFFFFF
activistTimeLabel=#8A4A23
activeBtnFore=#F7F1EB
activeBtnBg=#6E3D24
activeBtnSelect=#6E3D24
activeBtnBgSelect=#CFA682
activeBtnBlinkBorIn=#FFFFFF
importBtn3Fore=#FFFFFF
importBtn3Bg=#99491F
importBtn4Fore=#FFFFFF
importBtn4Bg=#A66A34
outputAreaBg=#F7F1EB
outputAreaFore1=#666666
outputAreaFore2=#7B3F1C
outputAreaBor=#C68352
configurableBtnBg=#C68352
importByEncryptBtnBg=#6E3D24
#main-scrollBar
handle=#7B3F1C
upBtn=#FFFFFF
downBtn=#FFFFFF
#about
aboutContentPaneBg=#F7F1EB
developerLabel=#7B3F1C
versionLabel=#B05E2E
recentlyDate=#8A4A23
statement=#8F324D
copyRight=#8F4A1E
#add
addContentPaneBg=#F7F1EB
textFieldBlinkBorIn1=#B05E2E
textFieldBlinkBorOut1=#D7B9A3
textFieldBlinkBorIn2=#B05E2E
textFieldBlinkBorOut2=#D7B9A3
textFieldBlinkBorIn3=#B05E2E
textFieldBlinkBorOut3=#D7B9A3
surePassBlinkBorIn=#B05E2E
surePassBlinkBorOut=#D7B9A3
textFieldBlinkBorIn4=#B05E2E
textFieldBlinkBorOut4=#D7B9A3
resetBtnFore=#FFFFFF
resetBtnBg=#D2A277
resetBtnBlinkBorIn=#FFFFFF
generateBtnFore=#FFFFFF
generateBtnBg=#C68352
generateBtnBlinkBorIn=#FFFFFF
submitBtnFore=#FFFFFF
submitBtnBg=#B96A36
submitBtnBlinkBorIn=#FFFFFF
#exportImport
pathTextFore=#8A4A23
pathTextLineBor=#D9B79E
chooseFileBtnFore=#FFFFFF
chooseFileBtnBg=#C68352
sureBtnFore=#FFFFFF
sureBtnBg=#8F4A1E
