#title
titleBg=#F1E3E8
closeBtnBgIn=#C43C45
miniBtnBgIn=#D6AFBC
mainPanelBg=#D6AFBC
#lock
lockBg=#F7F0F3
lockTipLabel=#7A314D
lockSecretText=#94405F
lockSecretTextBorder=#D7B3C1
loginTip=#6A2C44
isLocalBg=#A54E70
isLocalSelectBg=#C1849B
isCreateScene=#FFFFFF
isCreateSelectBg=#7A314D
isCreateBg=#E5CBD5
isLightWeightVersion=#FFFFFF
isLightBg=#94405F
isLightSelectBg=#F0DDE4
isLightBorder=#FFFFFF
isEng=#FFFFFF
isEngBg=#A54E70
isEngContextSelect=#FFFFFF
isEngContextSelectBg=#7A314D
isEngContext=#4F2436
isEngContextBg=#F3E7EC
isEngSelectBg=#94405F
lookFun=#FFFFFF
lookFunBg=#C1849B
#main
contentPaneBg=#F7F0F3
tableBg=#FAF4F7
tableSelectBg=#E8D3DB
tableSelectFore=#6A2C44
tableGrid=#D8BAC5
scrollPaneBg=#F7F0F3
scrollPaneBor=#C1849B
menuItemBlinkBgIn=#E5C769
menuItemBlinkBgOut=#F7F6F1
menuItemBlinkBorIn=#D8B84F
menuItemBlinkBorOut=#FFFFFF
searchTipFore=#7A314D
searchText=#7A314D
searchTextBlinkBorIn=#A54E70
searchTextBlinkBorOut=#E5CBD5
searchBtnFore=#FFFFFF
searchBtnBg=#7A314D
searchBtnBlinkBorIn=#FFFFFF
addBtnFore=#FFFFFF
addBtnBg=#A54E70
addBtnBlinkBorIn=#FFFFFF
resultNumbersFore=#6A2C44
copyAlertLabelFore=#C43C45
clearBtnFore=#FFFFFF
clearBtnBg=#C995A8
clearBtnBorderIn=#E8D3DB
realTimeBtnFore=#FFFFFF
realTimeBtnBg=#8A4A8F
realTimeBtnSelect=#C1849B
realTimeBtnBorderIn=#FFFFFF
switchBtnFore=#4F2436
switchBtnBg=#D0A3B2
switchBtnBorderIn=#FFFFFF
logBtnFore=#FFFFFF
logBtnBg=#94405F
logBtnBorderIn=#FFFFFF
funcBtnFore=#FFFFFF
funcBtnBg=#7A314D
funcBtnBorderIn=#FFFFFF
disclaimLabel=#D74C56
aboutBtnFore=#4F2436
aboutBtnBg=#EBD7DE
aboutBtnBlinkBorIn=#FFFFFF
exportBtnFore=#FFFFFF
exportBtnBg=#8A3B58
exportBtnBlinkBorIn=#FFFFFF
importBtnFore=#FFFFFF
importBtnBg=#A54E70
importBtnBlinkBorIn=#FFFFFF
activistTimeLabel=#94405F
activeBtnFore=#F5EDF1
activeBtnBg=#6A2C44
activeBtnSelect=#6A2C44
activeBtnBgSelect=#C995A8
activeBtnBlinkBorIn=#FFFFFF
importBtn3Fore=#FFFFFF
importBtn3Bg=#8A4A8F
importBtn4Fore=#FFFFFF
importBtn4Bg=#B36A86
outputAreaBg=#F7F0F3
outputAreaFore1=#666666
outputAreaFore2=#7A314D
outputAreaBor=#C1849B
configurableBtnBg=#C1849B
importByEncryptBtnBg=#6A2C44
#main-scrollBar
handle=#6A2C44
upBtn=#FFFFFF
downBtn=#FFFFFF
#about
aboutContentPaneBg=#F7F0F3
developerLabel=#6A2C44
versionLabel=#A54E70
recentlyDate=#8A3B58
statement=#8F324D
copyRight=#7A314D
#add
addContentPaneBg=#F7F0F3
textFieldBlinkBorIn1=#A54E70
textFieldBlinkBorOut1=#D8BAC5
textFieldBlinkBorIn2=#A54E70
textFieldBlinkBorOut2=#D8BAC5
textFieldBlinkBorIn3=#A54E70
textFieldBlinkBorOut3=#D8BAC5
surePassBlinkBorIn=#A54E70
surePassBlinkBorOut=#D8BAC5
textFieldBlinkBorIn4=#A54E70
textFieldBlinkBorOut4=#D8BAC5
resetBtnFore=#FFFFFF
resetBtnBg=#D0A3B2
resetBtnBlinkBorIn=#FFFFFF
generateBtnFore=#FFFFFF
generateBtnBg=#C1849B
generateBtnBlinkBorIn=#FFFFFF
submitBtnFore=#FFFFFF
submitBtnBg=#A54E70
submitBtnBlinkBorIn=#FFFFFF
#exportImport
pathTextFore=#7A314D
pathTextLineBor=#D6AFBC
chooseFileBtnFore=#FFFFFF
chooseFileBtnBg=#C1849B
sureBtnFore=#FFFFFF
sureBtnBg=#8A3B58
